apiVersion: v1
kind: Pod
metadata:
  name: learning-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
    - name: learning
      image: luckyganesh/learning
      ports:
        - containerPort: 8080
