apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chatmate-deploy
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: chatmate
    spec:
      containers:
        - name: chatmate
          image: mustakip/chatmate
          ports:
            - containerPort: 8080
